src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
#[ORM\Entity(repositoryClass: ProductRepository::class)]
class Product
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length:255, nullable: true)]
    /**
     * @Assert\NotBlank(groups={"product:new"},message="Le nom du produit ne peut pas être vide")
     * @Assert\Length(min=2,max=50,minMessage="Le nom du produit doit contenir au moins 2 caractere", maxMessage="Le nom du produit peut contenir jusqu'à 50 caractères")
     */
    private $name;

    #[ORM\Column(type: 'text', nullable: true)]
    /**
     * @Assert\NotBlank(groups={"product:edit"}, message="La description du produit ne peut pas être vide")
     * @Assert\Length(min=2,max=10000,minMessage="La description du produit doit contenir au moins 2 caractere", maxMessage="La description du produit peut contenir jusqu'à 10000 caractères")
     */
    private $description;

    #[ORM\Column(type: 'datetime', nullable: true)]
    private $createdAt;

    #[ORM\Column(type: 'string', length:255, nullable: true)]
    private $type;

    #[ORM\Column(type:'boolean', nullable: true)]
    /**
     * @Assert\Type(type="boolean", message="Aie, ça à mal fonctionné...")
     */
    private $isInWiki;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy:'products')]
    private $owner;

    #[ORM\Column(type: 'integer', nullable: true)]
    /**
     * @Assert\NotBlank(groups={"product:new"},message="La quantité ne peut pas être vide")
     * @Assert\Positive(message="La quantité doit être supérieure à 0")
     */
    private $amount;

    #[ORM\Column(type:'boolean', nullable: true)]
    /**
     * @Assert\Type(type="boolean", message="Aie, ça à mal fonctionné...")
     */
    private $isInInventory;

    #[ORM\OneToOne(targetEntity: Media::class, cascade: ['persist', 'remove'])]
    private $medias;

    #[ORM\OneToMany(mappedBy: 'product', targetEntity: Rate::class,  cascade:["remove"], orphanRemoval : true)]
    private $rates;

    #[ORM\Column(type:'boolean', nullable: true)]
    /**
     * @Assert\Type(type="boolean", message="Aie, ça à mal fonctionné...")
     */
    private $wiki;

    #[ORM\ManyToMany(targetEntity: Order::class, mappedBy: 'products', cascade: ["persist"])]
    private $orders;

    public function __construct()
    {
        $this->rates = new ArrayCollection();
        $this->orders = new ArrayCollection();
    }



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function getTypeStr(): ?string
    {
        if($this->getType() == "1")
        {
            return "Indica";
        }
        else {
            return "Sativa";
        }
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getIsInWiki(): ?bool
    {
        return $this->isInWiki;
    }

    public function setIsInWiki(bool $isInWiki): self
    {
        $this->isInWiki = $isInWiki;

        return $this;
    }

    public function getOwner(): ?User
    {
        return $this->owner;
    }

    public function setOwner(?User $owner): self
    {
        $this->owner = $owner;

        return $this;
    }

    public function getAmount(): ?int
    {
        return $this->amount;
    }

    public function setAmount(?int $amount): self
    {
        $this->amount = $amount;

        return $this;
    }

    public function getIsInInventory(): ?bool
    {
        return $this->isInInventory;
    }

    public function setIsInInventory(bool $isInInventory): self
    {
        $this->isInInventory = $isInInventory;

        return $this;
    }

    public function getMedias(): ?Media
    {
        return $this->medias;
    }

    public function setMedias(?Media $medias): self
    {
        $this->medias = $medias;

        return $this;
    }

    public function getRates(): int
    {
        if(count($this->rates) > 0) {
            $count = 0;
            foreach($this->rates as $rates)
            {
                $count += $rates->getRate();
                $rate = $count/count($this->rates);
            }
            return $rate;
        }
        else {
            return 0;
        }
    }

    /**
     * @return Collection<int, Product>
     */
    public function getAllRates(): Collection
    {
        return $this->rates;
    }

    public function addRate(Rate $rate): self
    {
        if (!$this->rates->contains($rate)) {
            $this->rates[] = $rate;
            $rate->setProduct($this);
        }

        return $this;
    }

    public function removeRate(Rate $rate): self
    {
        if ($this->rates->removeElement($rate)) {
            // set the owning side to null (unless already changed)
            if ($rate->getProduct() === $this) {
                $rate->setProduct(null);
            }
        }

        return $this;
    }

    public function getWiki(): ?bool
    {
        return $this->wiki;
    }

    public function setWiki(bool $wiki): self
    {
        $this->wiki = $wiki;

        return $this;
    }

    /**
     * @return Collection<int, Order>
     */
    public function getOrders(): Collection
    {
        return $this->orders;
    }

    public function addOrder(Order $order): self
    {
        if (!$this->orders->contains($order)) {
            $this->orders[] = $order;
            $order->addProduct($this);
        }

        return $this;
    }

    public function removeOrder(Order $order): self
    {
        if ($this->orders->removeElement($order)) {
            $order->removeProduct($this);
        }

        return $this;
    }

}

src/Form/ProductType.php
<?php

namespace App\Form;

use App\Entity\Product;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProductType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name', TextType::class, [
                "label" => "Variété"
            ])
            ->add('amount',NumberType::class, [
                "label" => "Quantité (g)"
            ])
            ->add('isPrintTag', CheckboxType::class, [
                "label" => "Imprimer une étiquette",
                "mapped" => false,
                "required" => false,
            ])
            ->add('delete', HiddenType::class, [
                "mapped" => false,
                "required" => false,
            ])
            ->add('medias', FileType::class, [
                "mapped" => false,
                "required" => false,
            ])
            ->add('type', ChoiceType::class, [
                "choices" => [
                    "Indica" => true,
                    "Sativa" => "Sativa"
                ],
                "expanded" => true,
                "multiple" => false,

            ])
            ->add('description', TextareaType::class, [
                "attr" => [
                    "rows" => "10"
                ]
            ])
            ->add('rate', TextType::class, [
                "mapped" => false,
                "required" => false
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Product::class,
        ]);
    }
}

src/Controller/ProductController.php
<?php

namespace App\Controller;

use App\Entity\Media;
use App\Entity\Order;
use App\Entity\Product;
use App\Entity\Rate;
use App\Form\OrderType;
use App\Form\ProductType;

use App\Repository\UserRepository;
use App\Repository\ProductRepository;
use App\Repository\RateRepository;
use App\Service\OrderManager;
use App\Service\ProductManager;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

/**
 * @Route("/product")
 */
class ProductController extends AbstractController
{
    private $productRepository;
    private $productManager;
    private $manager;
    private $rateRepository;

    public function __construct(ProductRepository $productRepository, ProductManager $productManager, EntityManagerInterface $manager, RateRepository $rateRepository)
    {
        $this->productRepository = $productRepository;
        $this->productManager = $productManager;
        $this->manager = $manager;
        $this->rateRepository = $rateRepository;
    }

    /**
     * @Route("/{id}", name="app_product_show")
     * @IsGranted("ROLE_USER", statusCode = 403, message="Vous devez être connecté pour accéder à cette page !")
     */
    public function show(Product $product, Request $request, UserRepository $userRepository): Response
    {
        $user = $userRepository->findOneBy(["username" => $request->getSession()->get("username")]);

        $inventoryProduct = $this->productRepository->findOneBy(["name" => $product->getName(), "isInInventory" => True, "owner" => $user]);
        
        return $this->render('product/show.html.twig', [
            'product' => $product,
            'inventory' => $inventoryProduct,
        ]);
    }

    /**
     * @Route("/wiki/{name}", name="app_product_getWiki")
     * @IsGranted("ROLE_USER", statusCode = 403, message="Vous devez être connecté pour accéder à cette page !")
     */
    public function getWiki($name)
    {
        $wikiProduct = $this->productRepository->findOneBy(["name" => $name, "wiki" => true]);

        return $this->redirectToRoute("app_product_show",["id" => $wikiProduct->getId()]);
    }

    /**
     * @Route("/{id}/rate", name="app_product_rate")
     * @IsGranted("ROLE_USER", statusCode = 403, message="Vous devez être connecté pour accéder à cette page !")
     */
    public function rate(Product $product,Request $request)
    {
        $userRate = $this->rateRepository->findOneBy(["user" => $this->getUser(), "product" => $product]);
        
        $form = $this->createForm(ProductType::class, $product);
        $form->handleRequest($request);

        if ($form->isSubmitted()) {
            $formRate = $form->get("rate")->getData();
            if ($formRate != null) {
                if ($userRate != null) {
                    $product->removeRate($userRate);
                }
                $rate = new Rate();
                $rate->setProduct($product)
                    ->setUser($this->getUser())
                    ->setRate($formRate);

                $this->manager->persist($rate);
                $product->addRate($rate);

                $this->manager->flush();
                $userRate = $rate;
            }
        }
        return $this->render('product/rate.html.twig', [
            "rates" => $this->rateRepository->findBy(["product" => $product->getId()]),
            "form" => $form->createView(),
            "userRate" => $userRate,
            "product" => $product
        ]);
    }

    /**
     * @Route("/{id}/addWiki", name="app_product_wiki")
     * @IsGranted("ROLE_USER", statusCode = 403, message="Vous devez être connecté pour accéder à cette page !")
     */
    public function addWiki(Request $request, Product $product, UserRepository $userRepository): Response
    {
        $user = $userRepository->findOneBy(["username" => $request->getSession()->get("username")]);
        $error = null;

        $form = $this->createForm(ProductType::class, $product, ["validation_groups" => ["product:edit", "Default"]]);
        $form->handleRequest($request);

        if ($form->isSubmitted()) {
            $formFile = $form->get("medias")->getData();
            $formRate = $form->get("rate")->getData();
            if($form->isValid())
            {
                $this->productManager->addWiki($user, $form, $product, $formFile);
                return $this->redirectToRoute('app_user_inventory', [], Response::HTTP_SEE_OTHER);

            }
            if($formFile === null) {
                $error["media"] = "Montrer-nous votre produit !";
            }
            if($formRate === null) {
                $error["rate"] = "Notez votre produit !";
            }
        }
        return $this->renderForm('product/addWiki.html.twig', [
            'product' => $product,
            'form' => $form,
            "error" => $error
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_product_edit")
     * @IsGranted("ROLE_USER", statusCode = 403, message="Vous devez être connecté pour accéder à cette page !")
     */
    public function edit(Request $request, Product $product, UserRepository $userRepository): Response
    {
        $user = $userRepository->findOneBy(["username" => $request->getSession()->get("username")]);

        $form = $this->createForm(ProductType::class, $product);
        $form->handleRequest($request);

        if ($form->isSubmitted()) {
            $this->productManager->edit($form, $product);
            return $this->redirectToRoute('app_product_show',['id' => $product->getId()]);
        }

        return $this->renderForm('product/edit.html.twig', [
            'product' => $product,
            'form' => $form
        ]);
    }

    /**
     * @Route("/deleteStock/{id}", name="app_product_deleteStock")
     * @IsGranted("ROLE_USER", statusCode = 403, message="Vous devez être connecté pour accéder à cette page !")
    */
    public function deleteStock(Product $product): Response
    {
        $this->productRepository->removeStock($product);

        return $this->redirectToRoute('app_user_inventory');
    }

    /**
     * @Route("/delete/{id}", name="app_product_delete")
     * @IsGranted("ROLE_USER", statusCode = 403, message="Vous devez être connecté pour accéder à cette page !")
    */
    public function delete(Product $product): Response
    {
        $products = $this->productRepository->findBy(['name' => $product->getName()]);
        foreach ($products as $product) {
            $product->setIsInWiki(false)
                    ->setWiki(false);
        }

        $this->manager->flush();

        return $this->redirectToRoute('app_home');
    }
}

templates/product/_delete_form.html.twig
<form method="post" action="{{ path('app_product_delete', {'id': product.id}) }}" onsubmit="return confirm('Etes-vous sûr de vouloir supprimer définitivement ce produit ?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ product.id) }}">
    <button class="button button--icon p-1 danger-color align-item-top"><i class="fas fa-trash-alt fa-2x"></i></button>
</form>

templates/product/_form.html.twig
{{ form_start(form, {"attr" : { "id" : "form-add"}}) }}
    <div class="flex-row d-flex justify-content-between">
        {{ form_errors(form) }}
        <div class="col-5 p-0">
            {{ form_label(form.name) }}</br>
            {{ form_widget(form.name, {"attr" : { "class" : "col-12 input-add"}}) }}
            {{ form_errors(form.name) }}

        </div>
        <div class="col-5 p-0">
            {{ form_label(form.amount) }}</br>
            {{ form_widget(form.amount, {"attr" : { "class" : "col-12 input-add"}}) }}
            {{ form_errors(form.amount) }}
        </div>
    </div>
    
    
    <button type="submit" class="button mt-3">Ajouter</button>

{{ form_widget(form._token) }}
{{ form_end(form, {'render_rest':false}) }}

templates/product/_search.html.twig
{% if products | length > 0 %}
    {% for product in products %}
        {% if product.medias | length > 0 %}
            <a href="{{ path('app_product_show',{'id' : product.id }) }}">
                <div class="main-frame mb-4 p-1 pb-3 pb-md-5 card-product">
                    <div class="d-flex flex-row flex-nowrap justify-content-around h-75">
                        {% if "http" in product.medias.path  %}
                            <img src="{{ product.medias.path }}" class="img-highlight mt-3" alt="image du produit">
                        {% else %}
                            <img src="{{ asset('medias/upload/' ~ product.medias.path ) }}" class="img-highlight mt-3" alt="image du produit">
                        {% endif %}
                        <div class="d-flex flex-column flex-nowrap w-50">
                            <strong><p class="font-color">{{ product.name }}</p></strong>
                            <p class="font-color">{{ product.typeStr }}</p>
                        </div>
                    </div>

                    <div class="mt-3">
                        {% include "shared/_stars.html.twig" %}
                    </div>
                    <p class="text-end mt-lg-4 me-3">Ajouté le {{ product.createdAt | date("d/m/Y") }}</p>
                </div>
            </a>
        {% endif %}
    {% endfor %}
{% else %}
    <p>Désolé aucun produit ne correspond à votre recherche :/</p>
{% endif %}

{% block javascripts %}
    <script type="text/javascript">
        $('#product-length').html("{{products | length }}");
    </script>
{% endblock %}
            

templates/product/addWiki.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter au wiki
{% endblock %}


{% block body %}
    <div class="main-frame main-frame--over main-frame--wiki scrollable p-1 ms-auto me-auto">
        <div class="d-flex flex-row flex-nowrap justify-content-start align-items-center">
            <a href=" {{app.request.headers.get('referer') }}"><p class="button button--icon button--small p-1"><i class="fas fa-long-arrow-alt-left fa-2x"></i></p></a>
            <h1 class="text-start mb-4 ms-auto me-auto">Ajouter au wiki</h1>
        </div>
        <hr class="m-0 mb-3"></hr>
        <h2>{{ product.name }}</h2>
        <div class="border-other-color ms-auto me-auto mt-3 d-flex flex-column justify-content-center product-preview" id="addWiki-preview">
            <img src="#" class="img-highlight w-100 border-none d-none" id="preview-wikiProduct">
            <i class="fas fa-camera fa-3x"></i>            
        </div>
        {{ form_start(form, {"attr" : {"class" : "form-wiki ms-auto me-auto mt-4"}}) }}

        {% if error.media is defined %}
            <p class="danger-color mt-3 mb-0">{{ error.media }}</p>
            {{ form_widget(form.medias, {"attr" : {"class" : "mt-2 border-danger", "onchange" : "previewImage(this)", "data-preview" : "addWiki-preview"}}) }}
        {% else %}
            {{ form_widget(form.medias, {"attr" : {"class" : "mt-2", "onchange" : "previewImage(this)", "data-preview" : "addWiki-preview"}}) }}
        {% endif %}

        {% if error.rate is defined %}
            <p class="danger-color mt-3 mb-0">{{ error.rate }}</p>
            <div class="mt-4 border-danger">
        {% else %}
            <div class="mt-4">
        {% endif %}

        {% for i in 1..10 %}
            <p class="d-inline-flex"><i class="far fa-star stars" id="star-{{ i }}"></i></p>
        {% endfor %}       
    </div>
    <div>
        {{ form_widget(form.rate, {"attr" : {"class": "d-none"}}) }}
        {{ form_widget(form.type, {"attr" : { "class" : "mt-3 justify-content-around d-flex flex-row"}}) }}
        {{ form_errors(form.type) }}
        {{ form_widget(form.description, {"attr" : {"placeholder" : "Description", "class" : "mt-2"}}) }}
        {{ form_errors(form.description) }}
        {{ form_widget(form.name, {"attr" : {"class": "d-none"}}) }}
        {{ form_widget(form.amount, {"attr" : {"class": "d-none"}}) }}
        <button type="submit" class="mt-3 mb-3 button">Ajouter</button>
        {{ form_widget(form._token) }}
        {{ form_end(form, {"render_rest" : false})}}
    </div>

    <script>
        $('#addWiki-preview').click(function() {
            $('#product_medias').click();
        })
    </script>
{% endblock %}

{% block javascripts %}
    <script src="{{ asset('js/rate.js') }}"></script>
{% endblock %}

templates/product/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Product{% endblock %}

{% block body %}
    <div class="main-frame main-frame--over main-frame--wiki scrollable p-1 ms-auto me-auto">
        <div class="d-flex flex-row flex-nowrap justify-content-start align-items-center">
            <a href=" {{app.request.headers.get('referer') }}"><p class="button button--icon button--small p-1"><i class="fas fa-long-arrow-alt-left fa-2x"></i></p></a>
            <h1 class="text-start mb-4 ms-auto me-auto">Modifier le produit</h1>
        </div>
        <hr class="m-0 mb-3"></hr>
        <h2>{{ product.name }}</h2>
        <div class="border-other-color ms-auto me-auto mt-3 d-flex flex-column justify-content-center product-preview">
            <img src="{{ asset("medias/upload/" ~ product.medias.path)}}" class="img-highlight w-100 border-none">
        </div>

        {# {% if product.medias | length > 0 %}
            <div class="img border-other-color ms-auto me-auto mt-3 preview" id="addWiki-preview" style="background-image: url('{{ asset("medias/upload/" ~ product.medias.path)}}')">
        {% else %}
            <div class="img border-other-color ms-auto me-auto mt-3 preview" id="addWiki-preview" style="background-image: url('{{ asset("medias/upload/default.jpg")}}')">
        {% endif %}
        </div> #}
        {{ form_start(form, {"attr" : { "novalidate" : true, "class" : "form-wiki ms-auto me-auto mt-4"}}) }}
        {{ form_widget(form.medias, {"attr" : { "class" : "mt-2", "onchange" : "previewImage(this)", "data-preview" : "addWiki-preview", "required" : "false"}}) }}
        {{ form_widget(form.type, {"attr" : { "class" : "mt-3 d-inline-flex justify-content-between w-75"}}) }}
        {{ form_widget(form.description, {"attr" : {"placeholder" : "Description", "class" : "mt-2"}}) }}
        {{ form_widget(form.name, {"attr" : {"class": "d-none"}}) }}
        {{ form_widget(form.amount, {"attr" : {"class": "d-none"}}) }}
        <button type="submit" class="mt-3 mb-3 button">Mettre à jour</button>
        {{ form_end(form, {"render_rest" : false})}}
    </div>
{% endblock %}

templates/product/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Product{% endblock %}

{% block body %}
    <div class="row align-items-center text-center p-4">
        <div class="col p-3 pt-0 ms-auto me-auto align-self-center second-bg border-other-color rounded font-color" id="box-login">
            <div class="row mt-1 border-bottom text-white mb-3">
                <div class="col border-end secondFont-bg p-2 rounded btn-switch" id="switch-inventory">
                    <h4>Inventaire</h4>
                </div>
                <div class="col secondFont-bg p-2 rounded btn-switch" id="switch-order">
                    <h4>Commande</h4>
                </div>
            </div>
            <div id="box-inventory">
                {{ include('product/_form.html.twig') }}
            </div>
            {# <div class="d-none" id="box-order">
                <h1>Ajoute une commande !</h1>
                <hr></hr>
                {{ include('order/_form.html.twig') }}
            </div> #}
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    <script src="{{ asset('js/order.js') }}"></script>
{% endblock %}

templates/product/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Product{% endblock %}

{% block body %}
    <div class="main-full-div">
        <div class="main-frame main-frame--over h-100 p-1 link-bottom ms-auto me-auto">
            <div class="d-flex flex-row flex-nowrap justify-content-around">
                {% if "http" in product.medias.path  %}
                    <img src="{{ product.medias.path }}" class="img-highlight img-highlight--show mt-3" alt="image du produit">
                {% else %}
                    <img src="{{ asset('medias/upload/' ~ product.medias.path ) }}" class="img-highlight img-highlight--show mt-3" alt="image du produit">
                {% endif %}
                <div class="d-flex flex-column flex-nowrap w-50">
                    <strong>
                        <h1 class="font-color">{{ product.name }}</h1>
                    </strong>
                    <p class="font-color">{{ product.typeStr }}</p>
                </div>
            </div>

            <div class="mt-3 stars--large">
                {% include "shared/_stars.html.twig" %}
            </div>
        </div>
        <div class="main-frame main-frame--over main-frame--show main-frame--white ms-auto me-auto p-2 link-all">
            <strong><p class="text-start">Reviews</p></strong>
            <div class="text-start publish-frame m-0 mb-3 p-3">
                <p>{{ product.description }}</p>
            </div>
        </div>
        <div class="main-frame main-frame--over main-frame--show p-1 link-top d-flex flex-row flex-nowrap justify-content-between ms-auto me-auto">
            <div class="d-flex flex-nowrap flex-row justify-content-around mt-2">
                <a href=" {{app.request.headers.get('referer') }}"><p class="button button--icon p-1"><i class="fas fa-long-arrow-alt-left fa-2x"></i></p></a>
                <a href="{{ path('app_product_edit', {'id': product.id}) }}"><p class="button button--icon p-1"><i class="far fa-edit fa-2x"></i></p></a>
                {% include('product/_delete_form.html.twig') %}  
            </div>
            <p class="mt-md-3 me-3">Ajouté le {{ product.createdAt | date("d/m/Y") }}</p>
        </div>
    </div>
{% endblock %}