src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
#[ORM\Entity(repositoryClass: ProductRepository::class)]
class Product
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length:255, nullable: true)]
    /**
     * @Assert\NotBlank(groups={"product:new"},message="Le nom du produit ne peut pas être vide")
     * @Assert\Length(min=2,max=50,minMessage="Le nom du produit doit contenir au moins 2 caractere", maxMessage="Le nom du produit peut contenir jusqu'à 50 caractères")
     */
    private $name;

    #[ORM\Column(type: 'text', nullable: true)]
    /**
     * @Assert\NotBlank(groups={"product:edit"}, message="La description du produit ne peut pas être vide")
     * @Assert\Length(min=2,max=10000,minMessage="La description du produit doit contenir au moins 2 caractere", maxMessage="La description du produit peut contenir jusqu'à 10000 caractères")
     */
    private $description;

    #[ORM\Column(type: 'datetime', nullable: true)]
    private $createdAt;

    #[ORM\Column(type: 'string', length:255, nullable: true)]
    private $type;

    #[ORM\Column(type:'boolean', nullable: true)]
    /**
     * @Assert\Type(type="boolean", message="Aie, ça à mal fonctionné...")
     */
    private $isInWiki;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy:'products')]
    private $owner;

    #[ORM\Column(type: 'integer', nullable: true)]
    /**
     * @Assert\NotBlank(groups={"product:new"},message="La quantité ne peut pas être vide")
     * @Assert\Positive(message="La quantité doit être supérieure à 0")
     */
    private $amount;

    #[ORM\Column(type:'boolean', nullable: true)]
    /**
     * @Assert\Type(type="boolean", message="Aie, ça à mal fonctionné...")
     */
    private $isInInventory;

    #[ORM\OneToOne(targetEntity: Media::class, cascade: ['persist', 'remove'])]
    private $medias;

    #[ORM\OneToMany(mappedBy: 'product', targetEntity: Rate::class,  cascade:["remove"], orphanRemoval : true)]
    private $rates;

    #[ORM\Column(type:'boolean', nullable: true)]
    /**
     * @Assert\Type(type="boolean", message="Aie, ça à mal fonctionné...")
     */
    private $wiki;

    #[ORM\ManyToMany(targetEntity: Order::class, mappedBy: 'products', cascade: ["persist"])]
    private $orders;

    public function __construct()
    {
        $this->rates = new ArrayCollection();
        $this->orders = new ArrayCollection();
    }



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function getTypeStr(): ?string
    {
        if($this->getType() == "1")
        {
            return "Indica";
        }
        else {
            return "Sativa";
        }
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getIsInWiki(): ?bool
    {
        return $this->isInWiki;
    }

    public function setIsInWiki(bool $isInWiki): self
    {
        $this->isInWiki = $isInWiki;

        return $this;
    }

    public function getOwner(): ?User
    {
        return $this->owner;
    }

    public function setOwner(?User $owner): self
    {
        $this->owner = $owner;

        return $this;
    }

    public function getAmount(): ?int
    {
        return $this->amount;
    }

    public function setAmount(?int $amount): self
    {
        $this->amount = $amount;

        return $this;
    }

    public function getIsInInventory(): ?bool
    {
        return $this->isInInventory;
    }

    public function setIsInInventory(bool $isInInventory): self
    {
        $this->isInInventory = $isInInventory;

        return $this;
    }

    public function getMedias(): ?Media
    {
        return $this->medias;
    }

    public function setMedias(?Media $medias): self
    {
        $this->medias = $medias;

        return $this;
    }

    public function getRates(): int
    {
        if(count($this->rates) > 0) {
            $count = 0;
            foreach($this->rates as $rates)
            {
                $count += $rates->getRate();
                $rate = $count/count($this->rates);
            }
            return $rate;
        }
        else {
            return 0;
        }
    }

    /**
     * @return Collection<int, Product>
     */
    public function getAllRates(): Collection
    {
        return $this->rates;
    }

    public function addRate(Rate $rate): self
    {
        if (!$this->rates->contains($rate)) {
            $this->rates[] = $rate;
            $rate->setProduct($this);
        }

        return $this;
    }

    public function removeRate(Rate $rate): self
    {
        if ($this->rates->removeElement($rate)) {
            // set the owning side to null (unless already changed)
            if ($rate->getProduct() === $this) {
                $rate->setProduct(null);
            }
        }

        return $this;
    }

    public function getWiki(): ?bool
    {
        return $this->wiki;
    }

    public function setWiki(bool $wiki): self
    {
        $this->wiki = $wiki;

        return $this;
    }

    /**
     * @return Collection<int, Order>
     */
    public function getOrders(): Collection
    {
        return $this->orders;
    }

    public function addOrder(Order $order): self
    {
        if (!$this->orders->contains($order)) {
            $this->orders[] = $order;
            $order->addProduct($this);
        }

        return $this;
    }

    public function removeOrder(Order $order): self
    {
        if ($this->orders->removeElement($order)) {
            $order->removeProduct($this);
        }

        return $this;
    }

}

templates/shared/_nav.html.twig
{% if app.user %}
    <div class="nav-circle nav-deploy flex-center justify-content-arround second-bg position-absolute bottom-0 end-0 white-text text-center mb-5 me-5 p-auto" id="nav-deploy">
        <div class="d-flex flex-column flex-nowrap justify-content-between h-100 p-1">
            <button type="button" class="text-white nav-link p-1" data-redirect="{{ path("app_logout") }}"><i class="fas fa-sign-out-alt fa-2x"></i></button>
            <button type="button" class="text-white p-1 link-disabled" data-redirect=""><i class="fas fa-cog fa-2x"></i></button>
        </div>
        <div class="d-flex flex-row flex-nowrap justify-content-between w-100 position-absolute p-1">
            <button type="button" class="text-white nav-link p-1" data-redirect="{{ path('app_user_inventory')}}"><i class="fas fa-shopping-bag fa-2x"></i></button>
            <button type="button" class="text-white nav-link p-1" data-redirect="{{ path('app_inventory-order') }}"><i class="fas fa-box fa-2x"></i></button>
        </div>
        <div class="flex-center position-absolute" id="nav">
            <div class="nav-circle nav-button flex-center secondFont-bg white-text">
                <button type="button" class="text-white z-20 m-0" id="btn-openNav"><i class="fas fa-bars fa-2x"></i></button>
                <button type="button" class="text-white z-20 d-none m-0 ms-auto me-auto" id="btn-closeNav"><i class="fas fa-times fa-2x"></i></button>
            </div>
        </div>
    </div>
{% endif %}

<script>
$( "#nav-deploy" ).draggable({
    addClasses: true,
    containment: "window"
});
</script>

templates/shared/_stars.html.twig
{% if product.rates != 0 %}
	{% for i in 1..product.rates %}
		<p class="d-inline-flex">
			<i class="fas fa-star other-font-color"></i>
		</p>
	{% endfor %}
	{% if product.rates < 10 %}
		{% for i in 1..10-product.rates %}
			<p class="d-inline-flex black-text">
				<i class="far fa-star"></i>
			</p>
		{% endfor %}
	{% endif %}

	{% set validRate = 0 %}
	{% for rate in product.allRates %}
		{% if rate.user.username == app.user.username %}
			{% set validRate = 1 %}
		{% endif %}
	{% endfor %}

	{% if validRate == 1 %}
		<a href="{{ path('app_product_rate', {'id' : product.id}) }}">
			<p class="ms-2 d-inline-flex success-color underline">({{ product.allRates | length }})</p>
		</a>
	{% else %}
		<a href="{{ path('app_product_rate', {'id' : product.id}) }}">
			<p class="ms-2 d-inline-flex danger-color underline">({{ product.allRates | length }})</p>
		</a>
	{% endif %}
{% endif %}